import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Head } from 'next/document'
import Navigation from './pages/page'
import Checkout from './checkout/page'
import Offers from './educationaloffers/page'
import Footer from './footer/page'




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Yulav Edutech',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <Checkout />
        <Offers />
        <Footer />
        {children}
      
      </body>
    </html>
  )
}
